### ISSUE TITLE
Add Option for Autostart with Windows

### ISSUE THREAD

**Issue by Dreamcooled** [Dreamcooled/sjupdater#27]

**Comment by Dreamcooled** [comment]
There's no option for this right now. But you can add a shortcut to the windows autostart folder, and add the "-nogui" parameter, to start sjupdater minimized.

**Comment by bagbag** [comment]
implemented (https://github.com/Dreamcooled/sjupdater/commit/4955e6811404733a5618931ad7746adecad0e22b)
