### ISSUE TITLE
introduce feature to sort and rearrange the home screen/list of series other than date-added

### ISSUE THREAD

**Issue by SimJoSt** [Dreamcooled/sjupdater#35]

**Comment by Dreamcooled** [comment]
Hei @SimJoSt 
Thanks for the feature request.
In case you haven't seen it yet: There's an option "Sort Tv Shows Alphabetically".

But I agree. We need custom sorting and reordering.

This ticket is strongly related to the older ticket #20, and I'm therefore closing this one in favor of the other.

**Comment by SimJoSt** [comment]
Hey @Dreamcooled 
No, I haven't seen it or tried it without a restart...
Perfect, now I will be a bit faster, thanks!
(although I am big fan of covers, I still like lists better ;-)
