### ISSUE TITLE
Series with State "In Production" are treated to be in "Unknown State"

### ISSUE THREAD

**Issue by Dreamcooled** [Dreamcooled/sjupdater#43]
See Homeland, right now.

**Comment by supporter** [comment]
Eine frage zu den Updateinfos "Shows end", "Next Serie airs in..."
Gilt das für die Orginal Serie in Deutsch/Englisch? Falls ja kann man das unter einstellungen evtl beifügen da ich deutsch natürlich eher bevorzuge und demensrechend auf sj dll warte.

Ansonsten klasse das du dies eingebaut hast!!!

**Comment by Dreamcooled** [comment]
@supporter ja gilt für die originalsprache. Leider hab ich keine möglichkeit die daten für andere Sprachen anzufragen. Am besten gleich auf google+ druck machen bei den entwicklern von tmdb und deren API  :)
