### ISSUE TITLE
Program is not starting

### ISSUE THREAD

**Issue by soprano1203** [Dreamcooled/sjupdater#44]
Hello,

the program is not starting and get the following exeption you see in the attachment. 
I also included the config.xml (rename .png to xml after downloading)

![config](https://cloud.githubusercontent.com/assets/15311377/10716344/248667d2-7b36-11e5-915d-7e2a42c301ee.png)
![25-10-2015 16-28-51](https://cloud.githubusercontent.com/assets/15311377/10716345/2489f708-7b36-11e5-89c5-5ae4b9c0d8f8.png)

.

I hope you can help me. 

Greets,

soprano1203

**Comment by Dreamcooled** [comment]
Hei. I cannot open your config (link is invalid, even after changing the extension).
Try deleting the file: C:\Users\Tim\AppData\Local\Sjupdater\SjUpdate.exe_*\0.41.0.0\user.config

Hope it helps.

**Comment by soprano1203** [comment]
It solves my problem, thank you!
