### ISSUE TITLE
sjupdat load-javascript for jd2

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#45]
Vorab, top Leistung!

Ich habe dan noch einen kleine Idee:
SJU starten wenn der JD ausgeführt wird und beendet sich automatisch, sofern keine Serien updates vorhanden sind. so ist man bequem uptodate und der sju wird etwas mehr im jd intigriert.
Ggf werden neue Folgen Automatisch in den JD Importiert und geladen ähnlich wie ein Feed.

Script startet nach Event-Trigger "JD Startet" den SJUpdater.exe mit befehl an serienjunkies.exe das dieser weiß das dieser von JD gestartet wurde und
beendet sjupdater sofern kein neuen Serienupdates der nächsten 20 oder x Minuten wieder.

optionaler Zusatz:
Durch Profil des sju wird neue Serie nach Spezifikation (hd/deutsch etc.) in den Linksammler geladen.
Eine vordefinierte JD-Regel (muss zuvor in den JD importiert werden und aktiv sein), das die Serie via JD  automatisch behandelt wird (spezifischer Downloadordner etc.)
Je nach Einstellung wird jd anschließen beendet.
ggf. wird captchaservice aktiviert/premium acc
Voraussetzung: 
Script stellt Zwischenablage an, nach Aktion auf Standard

Das könnte evtl Helfen:
https://board.jdownloader.org/showpost.php?p=113478&postcount=3

Wäre etwas davon  machbar?
lg Supporter :-)

**Comment by Dreamcooled** [comment]
ich glaub #61 deckt das jetzt mehr oder weniger ab
