### ISSUE TITLE
Serien Info's

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#46]
Für die ferne Zukunft wäre es klasse wenn Infos von MoviePilot.de gezogen und angezeigt werden.
Beispielsweise die Community-Bewertung und einige Infos zur Serie wie:
Serienstart (germany/orginal), Trailer (oder link dazu), Cover zur Staffel (zum laden https://github.com/Dreamcooled/sjupdater/issues/53 ), News der Serie (http://www.moviepilot.de/serie/homeland/news), Link um Kritik zu lesen, Link (Icon) zu Moviepilot bwz zur Serie/Staffel/Episode,
Optional: Serien-Chart Platzierung, Erstaustrahlung, jeder Folge
 Infos zur aktuellen Folgen, Trailer etc.)

Anregung:
Die Infos könnte man im Staffelbild der ausgewählten Serie anzeigen und den rest der Infos via Tab-Anordnung bei der Serienbeschreibung unterbringen

Beispiel für http://www.moviepilot.de/serie/homeland

lg Supporter weiter so!

**Comment by Dreamcooled** [comment]
Im moment nutze ich ja tmdb als Info-Provider.
https://www.themoviedb.org/tv/1407-homeland?language=de
Die haben halt eine super API, wo man alles anfragen kann, ohne das man die Website mühsam parsen muss. moviepilot.de hat leider keine API (mehr).

**Comment by supporter** [comment]
Okay das kann ich nachvolziehen. http://www.moviepilot.de/pages/faq#moviepilot_api
Jedenfalls würde ich es begrüßen wenn es die möglichkeit gäbe die Serieninfos (als Button zur Serie oder beim Klick aufs Cover) von Moviepilot zu beziehen.
An sich finde ich die zusammenfassungen und aufbau der Seite ganz gut.

**Comment by Dreamcooled** [comment]
ok. also einen link zu einer beliebigen seite.
ist mit #29 abgehandelt
