### ISSUE TITLE
Spezifische Regeln

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#49]
Ich bin mir nicht sicher ob diese Funktion schon so aktuell funktioniert, aber die Filter Regelung für einzelne Serien selbst zu definieren statt die Globale Einstellung zu nutzen wäre ebenfalls klasse.
Dabei sollte dann aber unter den Optionen>Default Filter "Globale Einstellung mit höherer Priorität" aktivieren/deaktivieren nicht fehlen bzw. Benutzerdefinierte Regeln aktivieren/deaktivieren/für alle zurücksetzen. Zusätzlich sollte doch die Möglichkeit bestehen die restlichen Folgen aus  SJ-Archiv anzuzeigen ohne die Regeln zurückzusetzen. Es könnte ja sein das eine Staffel/Episode gefiltert wird die nur in einer anderen Format/hoster verfügbar ist. Alternativ könnte man die Regel für diesen Fall eine ausmahne machen und alternative Hoster automatisch einblenden.

**Comment by Dreamcooled** [comment]
Also es gibt ja schon den Filter pro Serie. Klicke einfach auf das "Filter Icon" wenn du auf einer Serien-Übersicht bist. Was noch fehlt ist natürlich das zurücksetzen der benutzerdefinierten Regeln und das anschauen der restlichen (rausgefilterten Episoden).

**Comment by Dreamcooled** [comment]
#15 beschreibt das "zurücksetzen der Benutzerdefinierten Regeln"

**Comment by supporter** [comment]
Danke für das Feedback.
Okay, dachte das verählt sich wieder bei der globalenregel der "Einstellungen".
Vielleicht wäre es Hilfreich, das in der nächstenVersion in die Tooltips/Mpusovernachricht erwähnen, das diese Regel nicht global angewand wird, sondern nur auf die Ausgewählte Serie.

**Comment by Dreamcooled** [comment]
ok. Tooltip wird angepasst. (bzw der filter wird vermutlich eh grundsätzlich überarbeitet)
