### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#54]
Support (github) nativ unter Einstellungen n bzw im updater zeigen.

**Comment by Dreamcooled** [comment]
In der Titelleiste der Applikation hat es ja ein Icon was direkt zu Github führt.
Oder meinst du es bräuchte noch einen zusätzlichen Button?

**Comment by supporter** [comment]
Eigentlich ist das Symbol ausreichend, doch ich denke es kann nicht schaden einen Textbutton zu https://github.com/Dreamcooled/sjupdater/issues verlinken.
Ich denke nur das in dieser Statuszeile das hienin gehört. 
Deinen Codernamen sollte ebenfalls nicht fehlen!

**Comment by Dreamcooled** [comment]
ah das passt schon. Mein name ist ned soo wichtig :)
