### ISSUE TITLE
Accent (Theme)

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#55]
- accent dem dem windows (10) Standard anpassen!
- schwarz/grau/weiß hinzufügen

PS:
Vorab wünsch ich schon mal ein Frohes fest! :+1:

**Comment by Dreamcooled** [comment]
Ok. also eigene themes können wir nur umständlich einführen weil wir direkt das mahapps framework benutzen. Bitte dort einen request eröffnen für neue accents oder themes: https://github.com/MahApps/MahApps.Metro/issues
