### ISSUE TITLE
sjupdater not showing Downloads

### ISSUE THREAD

**Issue by GamesGamble** [Dreamcooled/sjupdater#57]
Teen Wolf Season 15 Episode 13 shows no 1080p download and at http://serienjunkies.org/teen-wolf/teen-wolf-season-5-hdtvweb-dl-sd720p1080p/ it has more than one for Episode 14 he is not showing anything (1080p availiable too) i dont have any exec configuration actuallly.
The Blacklist Season 3 Episode 11 is not showing 1080p, too and Episode 12 is available at http://serienjunkies.org/the-blacklist/the-blacklist-season-3-hdtv-sd720p/ but it doesnt show any link. The 100 Season 3 Episode 2 not showing any Links. The Flash Season 2 Episode 11 not showing any link. Marvels Agent Carter Season 2 Episode 3 not showing any link. The Arrow Season 4 Episode 11 not showing any link. It looks like he stopped working to sync from serienjunkies.org... Is there any logfile or something?

**Comment by Dreamcooled** [comment]
Me and someone else were not able to reproduce this. Are you still having such problems? if so: Please add another example.
