### ISSUE TITLE
Send personal statistic

### ISSUE THREAD

**Issue by supporter** [Dreamcooled/sjupdater#59]
Nun ich würde es begrüßen wenn die Daten Verschlüsselt (evtl. Tor-Netzwerk) gesendet werden.
Zusätzlich würde ich via Link eine Info beifügen, welche Daten übermittelt werden, das diese über Tor-Verschlüsselt versand werden, zu wechem zweck und zum Quellcode/GitHub link zum einsehen beigefügt wird.

Dies weckt vertrauen zu den Usern und sind bereitwilliger zu Supporten!

Zusätzlich könnte ein Bugreports ebenfalls versand werden.

**Comment by Dreamcooled** [comment]
Ok. Ja im Moment ist das noch etwas suboptimal. Und momentan wird eh nix ausgewertet was die User (falls Checkbox aktiviert) zusenden.

**Comment by bagbag** [comment]
Switched to HTTPS, not only at stats but also at updating (https://github.com/Dreamcooled/sjupdater/commit/ba4de0a0f298bcc8c11113ce5251e7a06324b691)

**Comment by bagbag** [comment]
Geht es dir hierbei um Sicherheit (Verschlüsselung) oder Anonymität (Tor)?

Falls letzteres, wäre HTTPS alleine ja nicht ausreichend... Daher nochmal geöffnet.

**Comment by bagbag** [comment]
Das einzige persönliche, was wir senden (sofern die Checkbox aktiviert ist), sind die shows. Da wir mit diesen nichts anstellen und sie somit nur unnötig die Berechnungszeit auf dem Server (Statistik der aktiven User) erhöht (da unwichtige Daten aus der Datenbank raussortiert werden), bin ich dafür, das das logging der shows zu entfernen.

**Comment by bagbag** [comment]
Ein Info Button gibt es seit fd479a4af55693e4d3cce26008ce147c2f9cee89.
Seit 8687931268036122e944b500951ce27f80f99fe2 wird nur noch Start, Termiante und Update gesendet. Ich sehe keinen Grund auf Tor o.Ä. zu setzten, daher ist dieser issue hiermit fertig.
