### ISSUE TITLE
noch paar Anregungen.

### ISSUE THREAD

**Issue by xyz0815xyz** [Dreamcooled/sjupdater#67]
hätte noch ein paar Anregungen.

1. Mark 'German Subbed' Episodes as German  von den Settings zu Filter bei den Serien Verschieben so das man von Serie zu Serie entscheiden kann ob mit untertittel anzeigt werden soll. (ist mir nicht wichtig)

2. URL für jede Serie klickt man auf die URL wird die eingegebene seit geöffnet zbs. 

http://www.wunschliste.de/serie/zoo/tv

3. Info Text zur jede Serie zbs. ich hasse diese Serie aber eine Freundin liebt sie deshalb lade ich Sie :-)

4.. Show Color für jede Serie so das man jede Serie farblich markieren kann

URL und Info könnte man mit einem kleinen Icon zbs. bei der Serie oder neben Open Filter , Clear Episoden-Cache einfügen

http://board.serienjunkies.org/index.php?page=Thread&postID=551275#post551275

könnte man zu denn Kategorien Shows with new Episodes , updated Episodes noch other Episodes hinzufügen. 
Specials wie zbs. Doctor.Who.S09S01.Weihnachtsspecial.Besuch.bei.River.Song werden zwar bei other angezeigt man bekommt aber keinen Hinweis das eine neue Folge gibt. 
Archer S04-S06  sind neu gibt zbs. nur als Staffel Pack wird zwar auch bei other angezeigt man bekommt aber auch keinen Hinweis.
Ab und zu kommen für ältere Serien DVD9 werden auch bei other angezeigt wäre auch schön wenn man dann einen Hinweis bekommen würde.

eine Rückmeldung was umgesetzt werden könnte und was nicht umgesetzt wird wäre schön.

**Comment by Dreamcooled** [comment]
Closing this for #68 #29 #69
