### ISSUE TITLE
SJU findet die neue Netflix Serie Love nicht

### ISSUE THREAD

**Issue by xyz0815xyz** [Dreamcooled/sjupdater#73]
SJU findet die neue Netflix Serie Love nicht

http://serienjunkies.org/love/love-staffel-1-web-sd720p1080p/

besteht die Möglichkeit solche Serien Manuel in die config einzutragen ist leider nicht die einzige Serie die SJU nicht findet.

**Comment by bagbag** [comment]
Das ist in der Tat ein Problem.
SjUpdater nutzt die Live-Suche von sj.org

![suche](https://cloud.githubusercontent.com/assets/4116942/13203829/53d588aa-d8c0-11e5-991d-4197abca152c.png)

Habe ich aber schon eine Problemlösung im Kopf, welche in kürze folgt :)

**Comment by bagbag** [comment]
Bilder sagen mehr als Worte:

![solution](https://cloud.githubusercontent.com/assets/4116942/13203934/309265d6-d8c3-11e5-8810-01a49fc1e609.png)
