### ISSUE TITLE
Series "Gate" empty

### ISSUE THREAD

**Issue by bagbag** [Dreamcooled/sjupdater#75]
http://serienjunkies.org/serie/gate/ has no seasons/episodes

**Comment by xyz0815xyz** [comment]
ist kein Bug Serie hat keine Deutsche oder Englische Tonspur nur Japanisch Tonspur mit deutschen Untertiteln.
Entweder Japanisch zu Deutsch und Englisch hinzufügen was  mit einem kleinen update stimmt schnell zu machen wäre oder einen haken bei Mark 'German Subbed' setzen was zur Folge hat das SJU diese bei allen Serien anzeigt.
