### ISSUE TITLE
app termination actions

### ISSUE THREAD

**Issue by Dreamcooled** [Dreamcooled/sjupdater#8]
Sometimes settings are not properly saved and the other stuff is not executed when the app is terminated.

**Comment by t-moe** [comment]
Seems to affect a couple of users, although it happens rarely.
In order to be able to start SjUpdater again you have to delete the config.xml file.

Tipp: Start SjUpdater from Dropbox, to have your config.xml saved all the time.

**Comment by Dreamcooled** [comment]
Seems to affect a couple of users, although it happens rarely.
In order to be able to start SjUpdater again you have to delete the config.xml file.

Tipp: Start SjUpdater from Dropbox, to have your config.xml saved all the time.

**Comment by Dreamcooled** [comment]
This is how the error looks like:
![image](https://cloud.githubusercontent.com/assets/3934991/8765686/9e7ab850-2e19-11e5-889e-bd31c9b0d127.png)

Working on a autobackup/restore trick, so that at least we can restore the old config when it happens....

**Comment by Dreamcooled** [comment]
The following improvements have been made:
* After successfully loading the config, a backup is made (config.xml.autobackup)
* If we cannot load the config on startup, we try to load the backup and show a messagebox.
* The config is now not only saved when you terminate the application, but also when you **Minimize** it
* In case everything fails we automatically create a new config file, instead of crashing. 

Hope this fixes the problem for the most users.
I'll close this ticket and reopen it, if it's still a problem later...
