### ISSUE TITLE
Updater: TLS problem

### ISSUE THREAD

**Issue by SimJoSt** [Dreamcooled/sjupdater#85]
Everytime time I open sjupdater, it shows me an "Updater Error" popup, telling me that the request was canceled, as it could not open a secure TLS channel.

![2018-02-02 19_54_49-updater error](https://user-images.githubusercontent.com/2992311/35749831-30ac315c-0853-11e8-8ff5-1e00b65b3985.png)

It seems like the whole functionality is broken due to that. First, everything still worked, then it didn't update the status of the series anymore, now not even the series images are shown.

**Comment by khalie** [comment]
check out http://serienjunkies.org/ or http://dokujunkies.org/ for yourself: they are both not reachable. I believe this might be the problem. SJUpdater just cant establish a connection to serienjunkies.org

**Comment by SimJoSt** [comment]
fixed by v0.50.1
